version: '2'
services:
  # web server
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    restart: always
    volumes:
      # app
      - ./app:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      - fpm

  # php-fpm
  fpm:
    build: ./php-fpm
    restart: always
    volumes:
      - ./app:/usr/share/nginx/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=ctf
      - DB_USERNAME=oss
      - DB_PASSWORD=3136b38330ee8dba21ca5a95aa2cd8b1
    depends_on:
      - mysql

  # database
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/initdb:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_DATABASE=ctf
      - MYSQL_USER=oss
      - MYSQL_PASSWORD=3136b38330ee8dba21ca5a95aa2cd8b1
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
